### ISSUE TITLE
Error: Cannot find module 'storj'

### ISSUE THREAD

**Issue by k06a** [Storj/storj.js#85]
Just tried to install and use:
```
npm install --save storj
```
test.js:
```
const Storj = require('storj');
```
Run:
```
truffle test
```
Output:
```
Error: Cannot find module 'storj'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/k06a/Projects/pre-alpha-base-contract/test/BaseContract.js:16:15)
    at Module._compile (module.js:612:30)
    at loader (/Users/k06a/Projects/pre-alpha-base-contract/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/k06a/Projects/pre-alpha-base-contract/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
```

**Comment by BrockAtkinson** [comment]
From the readme:
> Note: during the beta, this package will not be available via npm. Instead, install with the following syntax: `npm install --save https://github.com/storj/storj.js`

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
